sudo: false
language: cpp
compiler:
- gcc
# - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
#    - clang

script: 
- $CXX --version
- make -j travis


